- name: My Playbook
  hosts: "{{ servers }}"

  vars:
    user: kul

  tasks:
    - name: Print-1
      debug:
        msg: Hi from Ansible
    - name: Print-2
      debug:
        msg: Hi from {{ user }}
    - name: Print-3 With Condition
      debug:
        msg: Executing it as condition is met.
      when: user == "Kishore"
